# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f0752ca4d81f4565626d021dcfdee625db6561e31a3913ab0d955ea593fcbf1efeedfbb406a06c5c539966b1186ca5e8b599b6bbb475b088a79d14681a9b6c5

test:
  secret_key_base: 51a7dfe711a56b80e7314611ac56e78545a0efde12adc24e128fde4ab0435dae13734c8821a1379a15d10250ac6aa218f28cdffbccf687feaf17db88defd43ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
